'use client'

import { useState } from 'react';

export default function AIAssistantClient() {
  const [activeTool, setActiveTool] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState<string | null>(null);

  const tools = [
    {
      id: 'lesson',
      title: 'Generate Lesson Draft',
      icon: '📝',
      desc: 'Provide a topic and learning objectives, and AI will create a comprehensive lesson outline and content draft.',
      promptLabel: 'Topic & Objectives',
      placeholder: 'e.g., Introduction to React hooks...'
    },
    {
      id: 'quiz',
      title: 'Generate Quiz',
      icon: '❓',
      desc: 'Automatically generate multiple-choice questions based on existing lesson materials.',
      promptLabel: 'Source Material / Topic',
      placeholder: 'e.g., Generate 5 questions about Next.js Server Components...'
    },
    {
      id: 'rubric',
      title: 'Generate Rubric',
      icon: '📊',
      desc: 'Create detailed grading rubrics for practical assignments and portfolio submissions.',
      promptLabel: 'Assignment Description',
      placeholder: 'e.g., Final project requiring a full-stack e-commerce site...'
    },
    {
      id: 'risk',
      title: 'Identify At-Risk Learners',
      icon: '💡',
      desc: 'AI analyzes attendance and assessment data to highlight learners who may need intervention.',
      promptLabel: 'Course Selection',
      placeholder: 'Select a course to analyze...'
    },
    {
      id: 'feedback',
      title: 'Generate Feedback Draft',
      icon: '💬',
      desc: 'Draft constructive feedback for assignment submissions based on your rubric scores.',
      promptLabel: 'Submission Context',
      placeholder: 'e.g., Learner struggled with database joins but UI is excellent...'
    }
  ];

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    setIsGenerating(true);
    setResult(null);
    
    // Simulate AI generation delay
    setTimeout(() => {
      setIsGenerating(false);
      setResult("This is a simulated AI response generated by the Spectrum Built-in Simulation Engine. In the final product, this will connect to the active LLM provider to stream actual generated content based on your prompt.");
    }, 2000);
  };

  if (activeTool) {
    const tool = tools.find(t => t.id === activeTool);
    return (
      <div className="bg-white rounded-lg border shadow-sm p-6">
        <div className="flex items-center justify-between mb-6 border-b pb-4">
          <div className="flex items-center gap-3">
            <span className="text-3xl">{tool?.icon}</span>
            <h2 className="text-2xl font-bold text-gray-900">{tool?.title}</h2>
          </div>
          <button 
            onClick={() => { setActiveTool(null); setResult(null); }}
            className="text-gray-500 hover:text-gray-700 font-medium px-4 py-2 border rounded-md"
          >
            Back to Tools
          </button>
        </div>
        
        <form onSubmit={handleGenerate} className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">{tool?.promptLabel}</label>
            <textarea 
              required
              rows={4}
              className="w-full border-gray-300 rounded-md shadow-sm px-4 py-3 border focus:ring-blue-500 focus:border-blue-500"
              placeholder={tool?.placeholder}
            ></textarea>
          </div>
          
          <button 
            type="submit" 
            disabled={isGenerating}
            className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-6 rounded-md shadow-sm flex items-center gap-2"
          >
            {isGenerating ? (
              <>
                <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full"></div>
                Generating...
              </>
            ) : (
              <>
                <span>✨</span> Generate
              </>
            )}
          </button>
        </form>

        {result && (
          <div className="mt-8 pt-6 border-t">
            <h3 className="font-bold text-gray-900 mb-4">Generated Result</h3>
            <div className="bg-gray-50 rounded-lg p-6 border text-gray-700 whitespace-pre-wrap">
              {result}
            </div>
            <div className="mt-4 flex gap-3">
              <button className="bg-white border border-gray-300 rounded-md shadow-sm px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">
                Copy to Clipboard
              </button>
              <button className="bg-white border border-gray-300 rounded-md shadow-sm px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">
                Save as Draft
              </button>
            </div>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {tools.map(tool => (
        <button 
          key={tool.id}
          onClick={() => setActiveTool(tool.id)}
          className="bg-white rounded-lg border shadow-sm p-6 hover:border-blue-500 hover:shadow-md transition text-left focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
        >
          <div className="flex items-center gap-3 mb-4">
            <span className="text-2xl">{tool.icon}</span>
            <h3 className="font-bold text-gray-900">{tool.title}</h3>
          </div>
          <p className="text-sm text-gray-500">{tool.desc}</p>
        </button>
      ))}
    </div>
  );
}
